Issue#79 nuxt migration
sparcs-kaist/sparcs09 pull request #80
Opened 2017-10-18 15:48 UTC by ktk1012

* 기존 vue.js 코드를 nuxt로 migration
    * 유저 로그인, 회원가입, 마이페이지 page 구현
* nuxt 1.0-RC 버전에 추가된 spa 모드를 이용 (server side rendering은 없으나, 기타 프레임워크 유틸리티 활용 가능)

* test 방법
    * nuxt.config.js의 env 항목에 sso 관련 정보 및 api endpoint설정 (해당 api endpoint는 프록시를 탈 엔드포인트)
   * proxy 항목에 env 항목에서 설정한 api엔드 포인트를 실제 테스트용 백엔드 서버 주소로 변경

2017-10-19 11:24 UTC, samjo-nyang requested changes

2017-10-19 11:24 UTC, samjo-nyang commented on sparcs09-web/components/Logo.vue
> +<template>
지워도 되지 않을까요? (logo.png랑 favicon.ico도 마찬가지)

2017-10-19 11:24 UTC, samjo-nyang commented on sparcs09-web/nuxt.config.js
> +    SPARCS_SSO_CLIENT_ID: 'test9821043b531b2a8f',
하드코딩된 client_id를 덮어 쓸 수 있나요? 가능하다면 설정 방법을 README에 적어주시면 좋을거같습니다

2017-10-19 11:24 UTC, samjo-nyang commented on sparcs09-web/nuxt.config.js
> +    SPARCS09_API_DOMAIN: 'http://localhost:3000/api/'
이것도 host랑 port를 customize할 수 있었으면 좋겠습니다

2017-10-23 05:22 UTC, ktk1012 commented on sparcs09-web/components/Logo.vue
> +<template>
지우겠슴다.. 일단 기본 템플릿 구조 참조차 남겨뒀습니다.

2017-10-23 05:22 UTC, ktk1012 commented on sparcs09-web/nuxt.config.js
> +    SPARCS_SSO_CLIENT_ID: 'test9821043b531b2a8f',
client_id를 덮어 쓸 수 있는가 라는 말이 이해가 잘 안됩니다.. 설정 방법은 README에 오늘 중으로 추가하겠습니다. (실행방법은 일단 PR에 대략적으로 써두긴 했습니다.)

2017-10-23 05:23 UTC, ktk1012 commented on sparcs09-web/nuxt.config.js
> +    SPARCS09_API_DOMAIN: 'http://localhost:3000/api/'
이것도 README에 추가하겠습니다.

2017-10-23 06:46 UTC, samjo-nyang commented on sparcs09-web/nuxt.config.js
> +    SPARCS_SSO_CLIENT_ID: 'test9821043b531b2a8f',
client_id가 하드코딩되어있는데 env variable 같은걸로 바꿀 수 있는지 궁금합니다....

2017-10-25 14:46 UTC, samjo-nyang commented on sparcs09-web/.eslintrc.js
> +  extends: 'standard',
coding convention이 airbnb에서 standard로 바뀌었습니다...?

2017-10-29 07:53 UTC, ktk1012 commented on sparcs09-web/nuxt.config.js
> +    SPARCS_SSO_CLIENT_ID: 'test9821043b531b2a8f',
nuxt.config.js의 env 부분이 env variable을 설정하는 부분입니다.

2017-10-29 07:54 UTC, ktk1012 commented on sparcs09-web/.eslintrc.js
> +  extends: 'standard',
eslint설정을 제가 잘 모르는건지 airbnb로 수정하면 빌드에 계속 실패를 하고 있어..

2017-10-29 08:20 UTC, samjo-nyang commented
+ @ktk1012 앱 시작이 안됩니다.
```
ERROR  Failed to compile with 1 errors                                                                                                                                                                                                                             5:19:57 PM

This dependency was not found:

* /home/samjo/sparcs09/sparcs09-web/src/index.js in multi ./src/index.js

To install it, you can run: npm install --save /home/samjo/sparcs09/sparcs09-web/src/index.js
module.js:471
    throw err;
    ^

Error: Cannot find module '/home/samjo/sparcs09/sparcs09-web/build/main.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

2017-11-05 09:20 UTC, ktk1012 commented on sparcs09-web/components/Logo.vue
> +<template>
이 부분은 제가 메인페이지 작성 이슈를 진행하는 만큼 그 때 제거하도록 하겠습니다.

2017-11-05 09:20 UTC, ktk1012 commented on sparcs09-web/nuxt.config.js
> +    SPARCS_SSO_CLIENT_ID: 'test9821043b531b2a8f',
docs 수정했습니다.

2017-11-05 09:20 UTC, ktk1012 commented on sparcs09-web/nuxt.config.js
> +    SPARCS09_API_DOMAIN: 'http://localhost:3000/api/'
docs 수정! (2)

2017-11-05 09:22 UTC, ktk1012 commented
@samjo-nyang 실행 안되던 부분은 제가 테스트로 script 변경 한 부분이 있었는데 그 부분을 미처 안바꿔서 발생한 문제였습니다. 현재 수정해서 테스트 가능합니다

2017-11-05 11:50 UTC, samjo-nyang submitted a review, later dismissed

2017-11-05 11:54 UTC, samjo-nyang commented
LGTM! 수고하셨습니다! lint랑 rebase 한번만 해주세요!

2017-11-19 22:43 UTC, sugoiii approved these changes

2017-11-19 22:47 UTC, merged