item content api 구현 및 상품 소개 페이지 작업
sparcs-kaist/sparcs09 pull request #85
Opened 2017-12-06 02:05 UTC by ashe-sparcs

item content api가 apiary에 명시된 대로 구현되었습니다(reorder 제외).

상품 소개 페이지는 주문과 댓글의 api 연동을 제외한 상품 불러오기, 겉모양만 구현되었습니다.

2017-12-06 13:08 UTC, ktk1012 commented on sparcs09-web/components/forms/CommentForm.vue
> +      <p>김슈타인: </p>
김슈타인은 뭘까용??

2017-12-08 02:52 UTC, ashe-sparcs commented
댓글이 페이지네이션으로 되어 있던데 곧 구현하도록 하겠습니다.

2017-12-08 09:22 UTC, ktk1012 commented on sparcs09-web/components/forms/RecordForm.vue
> +      record_input: {
prop이 변경될수 있으니 data보다는 computed 속성을 쓰는게 좋아 보입니다.

2017-12-08 09:26 UTC, ktk1012 commented on sparcs09-web/pages/item/_id.vue
> +  async function getItemWithId(id) {
아이템 정보 같은게 vuex 스토어에 꼭 들어 있을 필요는 없기는 합니다만, 개인적으로는 vuex store에서 관리하는게 그래도 좋지 않을까? 하는 생각이 살짝 있네요.

2017-12-08 09:27 UTC, ktk1012 requested changes
프론트엔드의 구조 상에서는 큰 이슈는 없어 보입니다. 약간의 코멘트 확인만 부탁드릴게요

2017-12-16 13:58 UTC, ashe-sparcs commented on sparcs09-web/components/forms/RecordForm.vue
> +      record_input: {
prop 하고 연관된 option_items는 computed으로 변경했고, 연관되지 않은 quantity는 그대로 data에 두었습니다.

2017-12-16 13:58 UTC, ashe-sparcs commented on sparcs09-web/pages/item/_id.vue
> +  async function getItemWithId(id) {
vuex 개념이 아직 이해가 잘 안되어서 공부후에 나중에 적용할게요.

2017-12-19 08:10 UTC, ktk1012 commented on sparcs09-web/pages/item/_id.vue
> +  async function getItemWithId(id) {
일단 해당 부분은 최대한 빠르게 적용하는게 좋을 것 같은데 (전체 구조의 통일성을 위해서?) 일단 vuex를 훑어보는데에도 시간이 걸리긴 할테니 근 시일 내에 적용이 안될 것 같으면, async data를 vuex action으로 바꾸기 이슈를 하나 등록해주시면 좋겠습니당.

2017-12-19 08:16 UTC, ktk1012 approved these changes

2017-12-20 14:10 UTC, merged

2017-12-20 14:11 UTC, ashe-sparcs commented on sparcs09-web/pages/item/_id.vue
> +  async function getItemWithId(id) {
넹. vuex를 얼른 봐야겠네요 ㅜ